name: Performance Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache hyperfine
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-hyperfine
          restore-keys: |
            ${{ runner.os }}-hyperfine-

      - name: Install hyperfine (if not cached)
        run: |
          if [ ! -f ~/.cargo/bin/hyperfine ]; then
            cargo install hyperfine
          fi

      - name: Get changed projects
        id: detect-changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} HEAD)
          CHANGED_PROJECTS=$(echo "$CHANGED_FILES" | grep -E '^20[0-9]{2}/[0-9]+/' | cut -d'/' -f1,2 | uniq)
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Build project
        if: steps.detect-changes.outputs.changed_projects != ''
        run: |
          for PROJECT in ${{ steps.detect-changes.outputs.changed_projects }}; do
            dotnet restore "$PROJECT"
            dotnet build --configuration Release "$PROJECT"
          done

      - name: Run benchmark using hyperfile and send output to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: steps.detect-changes.outputs.changed_projects != ''
        run: |
          for PROJECT in ${{ steps.detect-changes.outputs.changed_projects }}; do
            EXE_PATH=$(find "$PROJECT/bin/Release/net9.0/" -type f -executable | head -n 1)
            if [ -z "$EXE_PATH" ]; then
              echo "No executable found for project: $PROJECT"
              continue
            fi
                        
            hyperfine "$EXE_PATH" --warmup 10 --export-markdown "$PROJECT/hyperfine.md"

             if [ -f "$PROJECT/hyperfine.md" ]; then
            output=$(cat "$PROJECT/hyperfine.md")
            escaped_output=$(echo "$output" | sed ':a;N;$!ba;s/\n/\\n/g')
            message="{\"content\": \"Benchmark results for **$project**:\n\`\`\`\n$escaped_output\n\`\`\`\"}"
            
            # Add sender field to payload (customized for your webhook)
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "$message" \
                 "${{ secrets.DISCORD_WEBHOOK_URL }}"
          fi
          done
