name: Performance Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Detect changed projects
      - name: Get changed projects
        id: detect-changes
        run: |
          # Fallback to HEAD^ if github.event.before is invalid
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ] || [ -z "${{ github.event.before }}" ]; then
            BEFORE="HEAD^"
          else
            BEFORE="${{ github.event.before }}"
          fi

          # Get changed files and extract top-level folders
          CHANGED_FILES=$(git diff --name-only "$BEFORE" HEAD)
          CHANGED_PROJECTS=$(echo "$CHANGED_FILES" | grep -E '^20[0-9]{2}/[0-9]+/' | cut -d'/' -f1,2 | uniq)

          # Debug output
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "Changed projects:"
          echo "$CHANGED_PROJECTS"

          # Export projects
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0 # Ändere dies auf deine benötigte .NET-Version

      # Benchmark each changed project
      - name: Run performance benchmark
        if: env.changed_projects != ''
        run: |
          for PROJECT in $CHANGED_PROJECTS; do
            echo "Benchmarking $PROJECT"
            dotnet restore $PROJECT
            dotnet build --configuration Release $PROJECT

            hyperfine "$PROJECT/bin/Release/net9.0/$PROJECT" --warmup 10 --export-markdown $PROJECT/benchmark_results.md

            # Sende die Ergebnisse an Discord
            if [ -f $PROJECT/benchmark_results.md ]; then
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\": \"\`\`\`markdown\n$(cat $PROJECT/benchmark_results.md)\n\`\`\`\"}" \
                   "${{ secrets.DISCORD_WEBHOOK_URL }}"
            fi
          done
        env:
          CHANGED_PROJECTS: ${{ env.changed_projects }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
